apiVersion: v1
kind: Pod
metadata:
  name: hdfs-client
  namespace: hdfs
spec:
  containers:
  - name: hdfs-client
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    command:
    - "tail"
    - "-f"
    - "/dev/null"