apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-resourcemanager
  namespace: hdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
  template:
    metadata:
      labels:
        app: hdfs
    spec:
      containers:
      - name: resourcemanager
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
        ports:
        - containerPort: 8088  # Web UI for ResourceManager
        env:
        - name: CLUSTER_NAME
          value: "hdfs-cluster"
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-resourcemanager
  namespace: hdfs
spec:
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: hadoop-resourcemanager
